============================= test session starts =============================
platform win32 -- Python 3.10.6, pytest-8.4.1, pluggy-1.6.0
rootdir: C:\Users\WiseDream\GitHub\AsleFlow
plugins: asyncio-1.0.0
asyncio: mode=strict, asyncio_default_fixture_loop_scope=None, asyncio_default_test_loop_scope=function
collected 8 items

tests\conftest.py ........                                               [100%]

============================== warnings summary ===============================
bot\models\models.py:9
  C:\Users\WiseDream\GitHub\AsleFlow\bot\models\models.py:9: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    Base = declarative_base()

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 8 passed, 1 warning in 0.39s =========================
